name: java script action for test
description: this action is a test of how using java script action 
inputs:
  version:
    description: 'CLI version to install'
    required: false
    default: "latest"

runs:
  using: "node21"
  main: "index.js"
