name: Deploy env
on:
  push:
    branches: ['Feature/*']
  workflow_dispatch: 
    inputs:
      first_name:
        required: true
        default: 'Abdullah'
jobs:
  build:
   environment:
     name: Production
   name: Hello world action
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: print event trigger
       run: echo "Triggered by ${{ github.event_name }}"
     - name: set the value
       run: echo "action_status=yellow" >> "$GITHUB_ENV"
     - name: use the value
       run: printf '%s/n "$action_status"
