name: A wf for my hello world file
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: 
    inputs:
      first_name:
        required: true
        default: 'Abdullah'
jobs:
  build:
   name: Hello world action
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
