name: using composite action
description: this action for testing a comosite action

on: push
jobs:
  using-composite:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: ./.github/actions/composite-actions/action.yml
       with:
         name: 'Abdullah'
  
