name: using js action
description: this action for testing a js action

on: push
jobs:
  using-js:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: ./.github/actions/js-action
       with:
         name: 'node17'
  
